### ISSUE TITLE
Imported audio convert .mp3 to .wav fails

### ISSUE THREAD

**Issue by rik-shaw** [wasta-linux/saymore-snap#2]
When attempt to annotate an imported .mp3 audio files, SayMore prompts that it needs to be converted to .wav. But then the conversion fails.

**Comment by n8marti** [comment]
It turns out that SayMore's included ffmpeg binaries are 64-bit. Revision #45 installs SayMore into a 64-bit wine prefix instead of 32-bit one. Can you confirm that this has been resolved for you in revision 45? Try removing the current 32-bit wine prefix with `saymore-unofficial.remove-wine-prefix`, then update to at least revision # 45 with `snap refresh saymore-unofficial --edge --devmode`, and try again.
